function(listSubDir RESULT ROOT_PATH)
    file(GLOB FILES RELATIVE ${ROOT_PATH} *)
    set(${RESULT} "")
    foreach(FILE_NAME ${FILES})
        if(IS_DIRECTORY "${ROOT_PATH}/${FILE_NAME}")
            if (${ARGC} GREATER "2")
                set(FILE_NAME ${FILE_NAME}.${ARGV2})
            endif()
            list(APPEND ${RESULT} ${FILE_NAME})
        endif()
    endforeach()
    set(${RESULT} ${${RESULT}} PARENT_SCOPE)
endfunction()

function(removeSuffix RESULT INPUT)
    string(FIND ${INPUT} "." DOT_POS REVERSE)
    string(SUBSTRING ${INPUT} "0" ${DOT_POS} ${RESULT})
    set(${RESULT} ${${RESULT}} PARENT_SCOPE)
endfunction()

